### ISSUE TITLE
getting failed to resolve error after adding dependencies in the build. gradle file.

### ISSUE THREAD

**Issue by PrafulKale123** [trustly/TrustlyAndroidSdk#6]
**Failed to resolve: trustly.android.library:trustly-android-library:+**  
tried with 
implementation 'trustly.android.library:trustly-android-library:3.0.1' aswell but getting same error

Failed to resolve: trustly.android.library:trustly-android-library:+
Show in Project Structure dialog
Affected Modules: app

**Comment by daniela-trustly** [comment]
Hi,
Did you add your github username and [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)  to the project level build.gradle?

Does your PAT have correct access rights? Depending on your github organisational settings you might also need to configure SSO for your token.

You can try opening in browser
https://maven.pkg.github.com/trustly/TrustlyAndroidSdk/trustly/android/library/trustly-android-library/3.0.1/trustly-android-library-3.0.1.pom

and entering your username and PAT
If this verification doesn't go through, then the PAT is not correctly configured.

**Comment by daniela-trustly** [comment]
Closing this issue since the SDK is distributed through maven central now.
Read more https://github.com/trustly/TrustlyAndroidSdk#integration
